package com.xworkz.collections;

import java.util.ArrayList;
import java.util.Collection;

public class Collectionss {

	public static void main(String[] args) {
		String festival1 = "Makara Sankranthi",festival2 = " Pongal",festival3 = "Basant Panchami",festival4 = "Maha Shivratri",festival5 = "Holi",festival6 = "Mewar",festival7 = "Baisakhi",festival8 = "Bihu",festivall8 = "Thrissur Pooram",festival9 = "Buddha Jayanti",festival10 = "EidUlFitr",festival11 = "Ratha Yatra",festival12 = "Hemis",festival13 = "Rakshabandhan",festival14 = "Janmashtmi",festival15 = "Independence Day",festival16 = "Onam",festival17 = "Ganesh Chaturthi",festival18 = "Navratri",festival19 = "Durga Puja",festival20 = "Dussehra",festival21 = "Diwali",festival22 = "Gurupurab",festival23 = "WAKAKUSA YAMAYAKI ",festival24 = "RIO CARNIVAL",festival25 = "SXSW",festival26 = "Thaipusam",festival27 = "Timkat",festival28 = "Kumbh Mela",festival29 = "Ramzan",festival30 = "Eid",festival31 = "Naga Panchami",festival32 = "new year",festival33 = "valitines",festival34 = "Venice Carnival",festival35 = "gowri",festival36 = "naraaka chaturdasi",festival37 = "Glastonbury",festival38 = "Christmas eve",festival39 = "good friday",festival40 = "mary day",festival41 = "repupbilc day",festival42 = "martyrs day",festival43 = "krishna janmastami",festival44 = "durga puja",festival45 = "govardhan puja",festival46 = "gandhi jayanthi",festival47 = "childerns day",festival48 = "tearchesr day",festival49 = "engnineers day",festival50 = "fathers day",festival51 = "mothers day",festival52 = "raksha bandhan",festival53 = "friendship day",festival54 = "Summerfest",festival55 = "world cup",festival56 = "ipl",festival57 = "Melbourne Cup",festival58 = " St. Patrick's Day",festival59 = "Easter",festival60 = "Bon";
		String actors1 = "puneet",actors2 = " rajkumar",actors3 = "shivraj kumar",actors4 = "yash",actors5 = "srk",actors6 = "salman khan",actors7 = "varun",actors8 = "shreyas",actorsl8 = "savitha",actors9 = "Buddha ",actors10 = "EidUlFitr",actors11 = "Radha ",actors12 = "Hemis",actors13 = "sudeep",actors14 = "krishna",actors15 = "dulquer",actors16 = "vishnuvardhan",actors17 = "Ganesh",actors18 = "disha",actors19 = "aamir",actors20 = "",actors21 = "chris",actors22 = "tom",actors23 = "brad ",actors24 = "steve",actors25 = "SXSW",actors26 = "Thaipusam",actors27 = "Timkat",actors28 = "vijay",actors29 = "Ramzan",actors30 = "Eid",actors31 = "Naga Panchami",actors32 = "new year",actors33 = "valitines",actors34 = "Venice ",actors35 = "gowri",actors36 = "naraaka chaturdasi",actors37 = "Glastonbury",actors38 = "steve",actors39 = "benidict",actors40 = "mahesh",actors41 = "srinivas",actors42 = "nikini",actors43 = "krishna ",actors44 = "ram",actors45 = "shankar nag",actors46 = "vikram",actors47 = "justin",actors48 = "michale",actors49 = "jhonson",actors50 = "fathers day",actors51 = "dwyane",actors52 = "batista",actors53 = "kane",actors54 = "ranbir",actors55 = "ranvir",actors56 = "harry",actors57 = "zyan",actors58 = "tom holland",actors59 = "Tom crsie",actors60 = "Bharat";
		String language1 = "kannada",language2 = " tamil",language3 = "telugu",language4 = "malyalam",language5 = "gujrathi",language6 = "marathi",language7 = "bojpuri",language8 = "hindi",languagel8 = "english",language9 = "chinese ",language10 = "uk english",language11 = "japanese ",language12 = "Hemis",language13 = "congo",language14 = "urdu",language15 = "spanish",language16 = "brazilian",language17 = "somali",language18 = "tatar",language19 = "turkish",language20 = "tajiki",language21 = "csinhala",language22 = "shona",language23 = "swedesh",language24 = "tagalog",language25 = "tibetian",language26 = "thai",language27 = "welsh",language28 = "xhosa",language29 = "bengali",language30 = "bismila",language31 = "arabic",language32 = "zulu",language33 = "aramainc",language34 = "danish",language35 = "dutch",language36 = "czech",language37 = "hausa",language38 = "hawaiina",language39 = "finnesh",language40 = "jarai",language41 = "mende",language42 = "polish",language43 = "punjabi",language44 = "malay",language45 = "mandarin",language46 = "nepali",language47 ="javanese",language48 = "lao",language49 = "latin",language50 = "sanskrit",language51 = "latvian", language52 = "igbo",language53 = "russian",language54 = "sebian",language55 = "shona",language56 = "sindhi",language57 = "swahili",language58 = "tirkmen",language59 = "uzbek",language60 = "yiddish";
		String movie1 = "rajkumara",movie2 = " appu",movie3 = "bahubali1",movie4 = "bahubali2",movie5 = "kgf",movie6 = "kgf2",movie7 = "misssion impossible1",movie8 = "misssion impossible2",moviel8 = "misssion impossible3",movie9 = "MI4 ",movie10 = "MI5",movie11 = "after earth ",movie12 = "after",movie13 = "after2",movie14 = "pushpa",movie15 = "spanish",movie16 = "brazilian oye",movie17 = "pirates and the carribiaen",movie18 = "pirates and the carribiaen",movie19 = "pirates and the carribiaen1",movie20 = "tajiki",movie21 = "pirates and the carribiaen2",movie22 = "pirates and the carribiaen3",movie23 = "swedesh",movie24 = "pirates and the carribiaen4",movie25 = "tibetian",movie26 = "titani",movie27 = "jumanji",movie28 = "jumanji2",movie29 = "bengali",movie30 = "bismila",movie31 = "arabic",movie32 = "zulu",movie33 = "qytre",movie34 = "danish",movie35 = "dutcherman",movie36 = "czech",movie37 = "hausa",movie38 = "i",movie39 = "finnesh",movie40 = "jarai",movie41 = "mende",movie42 = "polish",movie43 = "jannat",movie44 = "murder",movie45 = "avengers",movie46 = "captain america",movie47 ="sachin",movie48 = "lao",movie49 = "latin",movie50 = "iron man",movie51 = "end games", movie52 = "igbo",movie53 = "iron man2",movie54 = "sebian",movie55 = "iron man3",movie56 = "tanji",movie57 = "no more love",movie58 = "sipderman",movie59 = "black panther",movie60 = "iron man4";
		String webseries1 = "end games",webseries2 = " squid games",webseries3 = "squid games2",webseries4 = "got",webseries5 = "igt",webseries6 = "agt",webseries7 = "avgers",webseries8 = "vanda vision",webseriesl8 = "misssion impossible3",webseries9 = "MI4 ",webseries10 = "MI5",webseries11 = "after earth ",webseries12 = "after",webseries13 = "after we collided",webseries14 = "money hiest",webseries15 = "hallow man",webseries16 = "brazilian oye",webseries17 = "pirates and the carribiaen",webseries18 = "pirates and the carribiaen",webseries19 = "pirates and the carribiaen1",webseries20 = "tajiki",webseries21 = "pirates and the carribiaen2",webseries22 = "pirates and the carribiaen3",webseries23 = "swedesh",webseries24 = "pirates and the carribiaen4",webseries25 = "tibetian",webseries26 = "titani",webseries27 = "jumanji",webseries28 = "jumanji2",webseries29 = "bengali",webseries30 = "bismila",webseries31 = "arabic",webseries32 = "zulu",webseries33 = "ghost busters",webseries34 = "danish",webseries35 = "flash",webseries36 = "czech",webseries37 = "hausa",webseries38 = "i",webseries39 = "finnesh",webseries40 = "jarai",webseries41 = "mende",webseries42 = "polish",webseries43 = "jannat",webseries44 = "murder",webseries45 = "avengers",webseries46 = "captain america",webseries47 ="sachin",webseries48 = "lao",webseries49 = "latin",webseries50 = "iron man",webseries51 = "end games", webseries52 = "igbo",webseries53 = "iron man2",webseries54 = "sebian",webseries55 = "iron man3",webseries56 = "superman",webseries57 = "no more love",webseries58 = "sipderman far from home",webseries59 = "black panther",webseries60 = "vanda vison";
		String cities1 = "karnataka",cities2 = " tamil nadu",cities3 = "hyderbad",cities4 = "kerla",cities5 = "gujrath",cities6 = "maharastra",cities7 = "bangalore",cities8 = "mysore",citiesl8 = "canda",cities9 = "chinese ",cities10 = "uk english",cities11 = "japan ",cities12 = "Hemis",cities13 = "congo",cities14 = "mandya",cities15 = "span",cities16 = "brazil",cities17 = "somali",cities18 = "tatar",cities19 = "turkish",cities20 = "tajiki",cities21 = "csinhala",cities22 = "shona",cities23 = "swedesh",cities24 = "tagalog",cities25 = "tibet",cities26 = "thailand",cities27 = "welsh",cities28 = "xhosa",cities29 = "bengal",cities30 = "tengana",cities31 = "arab",cities32 = "zulu",cities33 = "aramainc",cities34 = "danish",cities35 = "dutch",cities36 = "czech",cities37 = "hausa",cities38 = "hawaiina",cities39 = "finnesh",cities40 = "jarai",cities41 = "mende",cities42 = "delhi",cities43 = "punjab",cities44 = "mangalore",cities45 = "madrid",cities46 = "nepali",cities47 ="javanese",cities48 = "lao",cities49 = "latin",cities50 = "somali",cities51 = "latvian", cities52 = "igbo",cities53 = "russia",cities54 = "sebian",cities55 = "up",cities56 = "ap",cities57 = "uttarakand",cities58 = "assam",cities59 = "bihar",cities60 = "uttar pradesh";
		String sweet1 = "mysorepak",sweet2 = " peda",sweet3 = "milk",sweet4 = "jammon",sweet5 = "gujrathi",sweet6 = "payasa",sweet7 = "bojpuri",sweet8 = "rasgulla",sweetl8 = "gelebi",sweet9 = "barfi ",sweet10 = "uk english",sweet11 = "japanese ",sweet12 = "Hemis",sweet13 = "congo",sweet14 = "urdu",sweet15 = "spanish",sweet16 = "kaju barfi",sweet17 = "somali",sweet18 = "tatar",sweet19 = "turkish",sweet20 = "tajiki",sweet21 = "darwad peda",sweet22 = "son papdi",sweet23 = "swedesh",sweet24 = "tagalog",sweet25 = "tibetian",sweet26 = "thai",sweet27 = "welsh",sweet28 = "xhosa",sweet29 = "bengali",sweet30 = "bismila",sweet31 = "arabic",sweet32 = "zulu",sweet33 = "aramainc",sweet34 = "danish",sweet35 = "dutch",sweet36 = "jaamon",sweet37 = "hausa",sweet38 = "hawaiina",sweet39 = "finnesh",sweet40 = "jarai",sweet41 = "mende",sweet42 = "polish",sweet43 = "punjabi",sweet44 = "malay",sweet45 = "mandarin",sweet46 = "nepali",sweet47 ="javanese",sweet48 = "lao",sweet49 = "icecream",sweet50 = "dessert",sweet51 = "pie", sweet52 = "igbo",sweet53 = "cake",sweet54 = "sebian",sweet55 = "shona",sweet56 = "jangeri",sweet57 = "kaja",sweet58 = "kunda",sweet59 = "doodh peda",sweet60 = "lassi";
		String bike1 = "java",bike2 = " rtr",bike3 = "apache",bike4 = "tvs",bike5 = "ola",bike6 = "ntorq",bike7 = "r15",bike8 = "hayabusa",bikel8 = "honda ",bike9 = "zmr ",bike10 = "gt",bike11 = "contenetal ",bike12 = "Hemis",bike13 = "congo",bike14 = "mt",bike15 = "duke",bike16 = "duke200",bike17 = "splendor",bike18 = "activa",bike19 = "dio",bike20 = "fascina",bike21 = " peda",bike22 = "son ",bike23 = "pulsar",bike24 = "ns220",bike25 = "ns160",bike26 = "rtr200",bike27 = "welsh",bike28 = "xhosa",bike29 = "suzuki",bike30 = "suzukisf",bike31 = "pulsur160",bike32 = "pulsar125",bike33 = "passion",bike34 = "hero",bike35 = "dutch",bike36 = "uber",bike37 = "hausa",bike38 = "hawaiina",bike39 = "finnesh",bike40 = "jarai",bike41 = "mende",bike42 = "polish",bike43 = "punjabi",bike44 = "malay",bike45 = "mandarin",bike46 = "nepali",bike47 ="javanese",bike48 = "lao",bike49 = "re",bike50 = "contenetal",bike51 = "intercerpto", bike52 = "igbo",bike53 = "ather",bike54 = "iqube",bike55 = "harley",bike56 = "bmw",bike57 = "tvsxl",bike58 = "kunda",bike59 = "zxr",bike60 = "ninja";
		String car1 = "bmw222",car2 = " audi",car3 = "jaguar",car4 = "benz",car5 = "rolls royce",car6 = "honda",car7 = "hynduai",car8 = "i10",carl8 = "honda ",car9 = "i20 ",car10 = "cityzx",car11 = "taata ",car12 = "harrier",car13 = "renault",car14 = "nissan",car15 = "spanish",car16 = "safari",car17 = "scorpio",car18 = " tesla",car19 = " tesla",car20 = " tesla" , car21 = " tesla",car22 = "modelx ",car23 = "bolero",car24 = "innova",car25 = "morris",car26 = "kia",car27 = "welsh",car28 = "xhosa",car29 = "suzuki",car30 = "suzukisf",car31 = "pulsur160",car32 = "pulsar125",car33 = "passion",car34 = "hero",car35 = "dutch",car36 = "uber",car37 = "hausa",car38 = "hawaiina",car39 = "finnesh",car40 = "jarai",car41 = "mende",car42 = "polish",car43 = "punjabi",car44 = "malay",car45 = "mandarin",car46 = "nepali",car47 ="javanese",car48 = "lao",car49 = "re",car50 = "contenetal",car51 = "intercerpto", car52 = "igbo",car53 = "ather",car54 = "iqube",car55 = "harley",car56 = "bmw",car57 = "nano",car58 = "benz",car59 = "modely",car60 = "audi2000x";
		String lipstick1 = "lakme",lipstick2 = " maybelline",lipstick3 = "elli18",lipstick4 = "Sugar",lipstick5 = "Insight",lipstick6 = "NYX.",lipstick7 = "L'Oreal Paris",lipstick8 = "Dior Rouge",lipstickl8 = "Huda Beauty ",lipstick9 = "MAC Retro Matte ",lipstick10 = "Kylie",lipstick11 = "Swiss Beauty ",lipstick12 = "NY",lipstick13 = "Kylie",lipstick14 = "Fenty",lipstick15 = "Maybelline ",lipstick16 = "Avon Color Lipstick Ignite";
		
		
		Collection collection = new ArrayList();
		collection.add(festival1);collection.add(festival2);collection.add(festival3);collection.add(festival4);collection.add(festival5);collection.add(festival6);collection.add(festival7);collection.add(festival8);collection.add(festival9);collection.add(festival10);collection.add(festival11);collection.add(festival12);collection.add(festival13);collection.add(festival14);collection.add(festival15);collection.add(festival16);collection.add(festival17);collection.add(festival18);collection.add(festival19);collection.add(festival20);collection.add(festival21);collection.add(festival22);collection.add(festival23);collection.add(festival24);collection.add(festival25);collection.add(festival26);collection.add(festival27);collection.add(festival28);collection.add(festival29);collection.add(festival30);collection.add(festival31);collection.add(festival32);collection.add(festival33);collection.add(festival34);collection.add(festival35);collection.add(festival36);collection.add(festival37);collection.add(festival38);collection.add(festival39);collection.add(festival40);collection.add(festival41);collection.add(festival42);collection.add(festival43);collection.add(festival44);collection.add(festival45);collection.add(festival46);collection.add(festival47);collection.add(festival48);collection.add(festival49);collection.add(festival50);collection.add(festival51);collection.add(festival52);collection.add(festival53);collection.add(festival54);collection.add(festival55);collection.add(festival56);collection.add(festival57);collection.add(festival58);collection.add(festival59);collection.add(festival60);

		Collection actorcollection = new ArrayList();
		actorcollection.add(actors1);actorcollection.add(actors2);actorcollection.add(actors3);actorcollection.add(actors4);actorcollection.add(actors5);actorcollection.add(actors6);actorcollection.add(actors7);actorcollection.add(actors8);actorcollection.add(actors9);actorcollection.add(actors10);actorcollection.add(actors11);actorcollection.add(actors12);actorcollection.add(actors13);actorcollection.add(actors14);actorcollection.add(actors15);actorcollection.add(actors16);actorcollection.add(actors17);actorcollection.add(actors18);actorcollection.add(actors19);actorcollection.add(actors20);actorcollection.add(actors21);actorcollection.add(actors22);actorcollection.add(actors23);actorcollection.add(actors24);actorcollection.add(actors25);actorcollection.add(actors26);actorcollection.add(actors27);actorcollection.add(actors28);actorcollection.add(actors29);actorcollection.add(actors30);actorcollection.add(actors31);actorcollection.add(actors32);actorcollection.add(actors33);actorcollection.add(actors34);actorcollection.add(actors35);actorcollection.add(actors36);actorcollection.add(actors37);actorcollection.add(actors38);actorcollection.add(actors39);actorcollection.add(actors40);actorcollection.add(actors41);actorcollection.add(actors42);actorcollection.add(actors43);actorcollection.add(actors44);actorcollection.add(actors45);actorcollection.add(actors46);actorcollection.add(actors47);actorcollection.add(actors48);actorcollection.add(actors49);actorcollection.add(actors50);actorcollection.add(actors51);actorcollection.add(actors52);actorcollection.add(actors53);actorcollection.add(actors54);actorcollection.add(actors55);actorcollection.add(actors56);actorcollection.add(actors57);actorcollection.add(actors58);actorcollection.add(actors59);actorcollection.add(actors60);

		Collection languagecollection = new ArrayList();
		languagecollection.add(language1);languagecollection.add(language2);languagecollection.add(language3);languagecollection.add(language4);languagecollection.add(language5);languagecollection.add(language6);languagecollection.add(language7);languagecollection.add(language8);languagecollection.add(language9);languagecollection.add(language10);languagecollection.add(language11);languagecollection.add(language12);languagecollection.add(language13);languagecollection.add(language14);languagecollection.add(language15);languagecollection.add(language16);languagecollection.add(language17);languagecollection.add(language18);languagecollection.add(language19);languagecollection.add(language20);languagecollection.add(language21);languagecollection.add(language22);languagecollection.add(language23);languagecollection.add(language24);languagecollection.add(language25);languagecollection.add(language26);languagecollection.add(language27);languagecollection.add(language28);languagecollection.add(language29);languagecollection.add(language30);languagecollection.add(language31);languagecollection.add(language32);languagecollection.add(language33);languagecollection.add(language34);languagecollection.add(language35);languagecollection.add(language36);languagecollection.add(language37);languagecollection.add(language38);languagecollection.add(language39);languagecollection.add(language40);languagecollection.add(language41);languagecollection.add(language42);languagecollection.add(language43);languagecollection.add(language44);languagecollection.add(language45);languagecollection.add(language46);languagecollection.add(language47);languagecollection.add(language48);languagecollection.add(language49);languagecollection.add(language50);languagecollection.add(language51);languagecollection.add(language52);languagecollection.add(language53);languagecollection.add(language54);languagecollection.add(language55);languagecollection.add(language56);languagecollection.add(language57);languagecollection.add(language58);languagecollection.add(language59);languagecollection.add(language60);

		Collection moviecollection = new ArrayList();
		moviecollection.add(movie1);moviecollection.add(movie2);moviecollection.add(movie3);moviecollection.add(movie4);moviecollection.add(movie5);moviecollection.add(movie6);moviecollection.add(movie7);moviecollection.add(movie8);moviecollection.add(movie9);moviecollection.add(movie10);moviecollection.add(movie11);moviecollection.add(movie12);moviecollection.add(movie13);moviecollection.add(movie14);moviecollection.add(movie15);moviecollection.add(movie16);moviecollection.add(movie17);moviecollection.add(movie18);moviecollection.add(movie19);moviecollection.add(movie20);moviecollection.add(movie21);moviecollection.add(movie22);moviecollection.add(movie23);moviecollection.add(movie24);moviecollection.add(movie25);moviecollection.add(movie26);moviecollection.add(movie27);moviecollection.add(movie28);moviecollection.add(movie29);moviecollection.add(movie30);moviecollection.add(movie31);moviecollection.add(movie32);moviecollection.add(movie33);moviecollection.add(movie34);moviecollection.add(movie35);moviecollection.add(movie36);moviecollection.add(movie37);moviecollection.add(movie38);moviecollection.add(movie39);moviecollection.add(movie40);moviecollection.add(movie41);moviecollection.add(movie42);moviecollection.add(movie43);moviecollection.add(movie44);moviecollection.add(movie45);moviecollection.add(movie46);moviecollection.add(movie47);moviecollection.add(movie48);moviecollection.add(movie49);moviecollection.add(movie50);moviecollection.add(movie51);moviecollection.add(movie52);moviecollection.add(movie53);moviecollection.add(movie54);moviecollection.add(movie55);moviecollection.add(movie56);moviecollection.add(movie57);moviecollection.add(movie58);moviecollection.add(movie59);moviecollection.add(movie60);

		Collection webseriescollection = new ArrayList();
		webseriescollection.add(webseries1);webseriescollection.add(webseries2);webseriescollection.add(webseries3);webseriescollection.add(webseries4);webseriescollection.add(webseries5);webseriescollection.add(webseries6);webseriescollection.add(webseries7);webseriescollection.add(webseries8);webseriescollection.add(webseries9);webseriescollection.add(webseries10);webseriescollection.add(webseries11);webseriescollection.add(webseries12);webseriescollection.add(webseries13);webseriescollection.add(webseries14);webseriescollection.add(webseries15);webseriescollection.add(webseries16);webseriescollection.add(webseries17);webseriescollection.add(webseries18);webseriescollection.add(webseries19);webseriescollection.add(webseries20);webseriescollection.add(webseries21);webseriescollection.add(webseries22);webseriescollection.add(webseries23);webseriescollection.add(webseries24);webseriescollection.add(webseries25);webseriescollection.add(webseries26);webseriescollection.add(webseries27);webseriescollection.add(webseries28);webseriescollection.add(webseries29);webseriescollection.add(webseries30);webseriescollection.add(webseries31);webseriescollection.add(webseries32);webseriescollection.add(webseries33);webseriescollection.add(webseries34);webseriescollection.add(webseries35);webseriescollection.add(webseries36);webseriescollection.add(webseries37);webseriescollection.add(webseries38);webseriescollection.add(webseries39);webseriescollection.add(webseries40);webseriescollection.add(webseries41);webseriescollection.add(webseries42);webseriescollection.add(webseries43);webseriescollection.add(webseries44);webseriescollection.add(webseries45);webseriescollection.add(webseries46);webseriescollection.add(webseries47);webseriescollection.add(webseries48);webseriescollection.add(webseries49);webseriescollection.add(webseries50);webseriescollection.add(webseries51);webseriescollection.add(webseries52);webseriescollection.add(webseries53);webseriescollection.add(webseries54);webseriescollection.add(webseries55);webseriescollection.add(webseries56);webseriescollection.add(webseries57);webseriescollection.add(webseries58);webseriescollection.add(webseries59);webseriescollection.add(webseries60);

		Collection citiescollection = new ArrayList();
		citiescollection.add(cities1);citiescollection.add(cities2);citiescollection.add(cities3);citiescollection.add(cities4);citiescollection.add(cities5);citiescollection.add(cities6);citiescollection.add(cities7);citiescollection.add(cities8);citiescollection.add(cities9);citiescollection.add(cities10);citiescollection.add(cities11);citiescollection.add(cities12);citiescollection.add(cities13);citiescollection.add(cities14);citiescollection.add(cities15);citiescollection.add(cities16);citiescollection.add(cities17);citiescollection.add(cities18);citiescollection.add(cities19);citiescollection.add(cities20);citiescollection.add(cities21);citiescollection.add(cities22);citiescollection.add(cities23);citiescollection.add(cities24);citiescollection.add(cities25);citiescollection.add(cities26);citiescollection.add(cities27);citiescollection.add(cities28);citiescollection.add(cities29);citiescollection.add(cities30);citiescollection.add(cities31);citiescollection.add(cities32);citiescollection.add(cities33);citiescollection.add(cities34);citiescollection.add(cities35);citiescollection.add(cities36);citiescollection.add(cities37);citiescollection.add(cities38);citiescollection.add(cities39);citiescollection.add(cities40);citiescollection.add(cities41);citiescollection.add(cities42);citiescollection.add(cities43);citiescollection.add(cities44);citiescollection.add(cities45);citiescollection.add(cities46);citiescollection.add(cities47);citiescollection.add(cities48);citiescollection.add(cities49);citiescollection.add(cities50);citiescollection.add(cities51);citiescollection.add(cities52);citiescollection.add(cities53);citiescollection.add(cities54);citiescollection.add(cities55);citiescollection.add(cities56);citiescollection.add(cities57);citiescollection.add(cities58);citiescollection.add(cities59);citiescollection.add(cities60);

		Collection sweetcollection = new ArrayList();
		sweetcollection.add(sweet1);sweetcollection.add(sweet2);sweetcollection.add(sweet3);sweetcollection.add(sweet4);sweetcollection.add(sweet5);sweetcollection.add(sweet6);sweetcollection.add(sweet7);sweetcollection.add(sweet8);sweetcollection.add(sweet9);sweetcollection.add(sweet10);sweetcollection.add(sweet11);sweetcollection.add(sweet12);sweetcollection.add(sweet13);sweetcollection.add(sweet14);sweetcollection.add(sweet15);sweetcollection.add(sweet16);sweetcollection.add(sweet17);sweetcollection.add(sweet18);sweetcollection.add(sweet19);sweetcollection.add(sweet20);sweetcollection.add(sweet21);sweetcollection.add(sweet22);sweetcollection.add(sweet23);sweetcollection.add(sweet24);sweetcollection.add(sweet25);sweetcollection.add(sweet26);sweetcollection.add(sweet27);sweetcollection.add(sweet28);sweetcollection.add(sweet29);sweetcollection.add(sweet30);sweetcollection.add(sweet31);sweetcollection.add(sweet32);sweetcollection.add(sweet33);sweetcollection.add(sweet34);sweetcollection.add(sweet35);sweetcollection.add(sweet36);sweetcollection.add(sweet37);sweetcollection.add(sweet38);sweetcollection.add(sweet39);sweetcollection.add(sweet40);sweetcollection.add(sweet41);sweetcollection.add(sweet42);sweetcollection.add(sweet43);sweetcollection.add(sweet44);sweetcollection.add(sweet45);sweetcollection.add(sweet46);sweetcollection.add(sweet47);sweetcollection.add(sweet48);sweetcollection.add(sweet49);sweetcollection.add(sweet50);sweetcollection.add(sweet51);sweetcollection.add(sweet52);sweetcollection.add(sweet53);sweetcollection.add(sweet54);sweetcollection.add(sweet55);sweetcollection.add(sweet56);sweetcollection.add(sweet57);sweetcollection.add(sweet58);sweetcollection.add(sweet59);sweetcollection.add(sweet60);

		Collection bikecollection = new ArrayList();
		bikecollection.add(bike1);bikecollection.add(bike2);bikecollection.add(bike3);bikecollection.add(bike4);bikecollection.add(bike5);bikecollection.add(bike6);bikecollection.add(bike7);bikecollection.add(bike8);bikecollection.add(bike9);bikecollection.add(bike10);bikecollection.add(bike11);bikecollection.add(bike12);bikecollection.add(bike13);bikecollection.add(bike14);bikecollection.add(bike15);bikecollection.add(bike16);bikecollection.add(bike17);bikecollection.add(bike18);bikecollection.add(bike19);bikecollection.add(bike20);bikecollection.add(bike21);bikecollection.add(bike22);bikecollection.add(bike23);bikecollection.add(bike24);bikecollection.add(bike25);bikecollection.add(bike26);bikecollection.add(bike27);bikecollection.add(bike28);bikecollection.add(bike29);bikecollection.add(bike30);bikecollection.add(bike31);bikecollection.add(bike32);bikecollection.add(bike33);bikecollection.add(bike34);bikecollection.add(bike35);bikecollection.add(bike36);bikecollection.add(bike37);bikecollection.add(bike38);bikecollection.add(bike39);bikecollection.add(bike40);bikecollection.add(bike41);bikecollection.add(bike42);bikecollection.add(bike43);bikecollection.add(bike44);bikecollection.add(bike45);bikecollection.add(bike46);bikecollection.add(bike47);bikecollection.add(bike48);bikecollection.add(bike49);bikecollection.add(bike50);bikecollection.add(bike51);bikecollection.add(bike52);bikecollection.add(bike53);bikecollection.add(bike54);bikecollection.add(bike55);bikecollection.add(bike56);bikecollection.add(bike57);bikecollection.add(bike58);bikecollection.add(bike59);bikecollection.add(bike60);

		Collection carcollection = new ArrayList();
		carcollection.add(car1);carcollection.add(car2);carcollection.add(car3);carcollection.add(car4);carcollection.add(car5);carcollection.add(car6);carcollection.add(car7);carcollection.add(car8);carcollection.add(car9);carcollection.add(car10);carcollection.add(car11);carcollection.add(car12);carcollection.add(car13);carcollection.add(car14);carcollection.add(car15);carcollection.add(car16);carcollection.add(car17);carcollection.add(car18);carcollection.add(car19);carcollection.add(car20);carcollection.add(car21);carcollection.add(car22);carcollection.add(car23);carcollection.add(car24);carcollection.add(car25);carcollection.add(car26);carcollection.add(car27);carcollection.add(car28);carcollection.add(car29);carcollection.add(car30);carcollection.add(car31);carcollection.add(car32);carcollection.add(car33);carcollection.add(car34);carcollection.add(car35);carcollection.add(car36);carcollection.add(car37);carcollection.add(car38);carcollection.add(car39);carcollection.add(car40);carcollection.add(car41);carcollection.add(car42);carcollection.add(car43);carcollection.add(car44);carcollection.add(car45);carcollection.add(car46);carcollection.add(car47);carcollection.add(car48);carcollection.add(car49);carcollection.add(car50);carcollection.add(car51);carcollection.add(car52);carcollection.add(car53);carcollection.add(car54);carcollection.add(car55);carcollection.add(car56);carcollection.add(car57);carcollection.add(car58);carcollection.add(car59);carcollection.add(car60);

		Collection lipstickcollection = new ArrayList();
		lipstickcollection.add(lipstick1);lipstickcollection.add(lipstick2);lipstickcollection.add(lipstick3);lipstickcollection.add(lipstick4);lipstickcollection.add(lipstick5);lipstickcollection.add(lipstick6);lipstickcollection.add(lipstick7);lipstickcollection.add(lipstick8);lipstickcollection.add(lipstick9);lipstickcollection.add(lipstick10);lipstickcollection.add(lipstick11);lipstickcollection.add(lipstick12);lipstickcollection.add(lipstick13);lipstickcollection.add(lipstick14);lipstickcollection.add(lipstick15);lipstickcollection.add(lipstick16);
		
		
		System.out.println("Number of Festivals added is : " + collection.size());
		System.out.println("Number of Actors added is : " + actorcollection.size());
		System.out.println("Number of Languages added is : " + languagecollection.size());
		System.out.println("Number of Movies added is : " + moviecollection.size());
		System.out.println("Number of Web Series  added is : " + webseriescollection.size());
		System.out.println("Number of Cities  added is : " + citiescollection.size());
		System.out.println("Number of Sweets  added is : " + sweetcollection.size());
		System.out.println("Number of Bikes  added is : " + bikecollection.size());
		System.out.println("Number of Cars  added is : " + carcollection.size());
		System.out.println("Number of Lipsticks  added is : " + lipstickcollection.size());



		





		

	}

}
